- type: job
  parent: CMJobBase
  id: RMCEliteMercMEngineer
  name: Elite Engineer Mercenary
  description: rmc-ghost-role-information-pmc-description
  playTimeTracker: RMCEliteMercEngineer
  startingGear: RMCEliteMercEngineer
  joinNotifyCrew: false
  accessGroups:
  - Colony
  spawnMenuRoleName: Elite Mercenary Engineer
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Mercenary
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillFirearms: 2
        RMCSkillMedical: 1
        RMCSkillFireman: 2
        RMCSkillConstruction: 3
        RMCSkillEngineer: 4
        RMCSkillEndurance: 5
        RMCSkillVehicles: 1
        RMCSkillPilot: 2
        RMCSkillJtac: 1
        RMCSkillMeleeWeapons: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: rmc-job-prefix-merc-engineer
  hidden: true

- type: startingGear
  id: RMCEliteMercEngineer
  equipment:
    id: RMCIDCardMercenary
    jumpsuit: RMCJumpsuitMercenaryEngineer
    outerClothing: RMCArmorMercenaryEngineer
    gloves: RMCHandsVeteran
    eyes: CMGlassesM42ScoutSight
    head: RMCArmorHelmetMercenaryEngineer
    shoes: RMCBootsPMCFilled
    mask: RMCMaskBalaclavaPMC
    ears: RMCHeadsetDistressDukes
    back: RMCSatchelLightpackWelder
    belt: RMCMotionDetector
    pocket1: RMCPouchShotgunLarge
    pocket2: RMCPouchToolsSocMarineRaiderFill # TODO RMC14: PMC re-sprite
    suitstorage: WeaponShotgunM890
  storage:
    storage:
    outerClothing:
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    back:
    - RMCBoxAttachment
    - RMCExplosivePlastic
    - CMPacketGrenadeFragFilled
    - RMCPacketGrenadeSmokeFilled
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot
    - CMShellShotgunBuckshot


# These guys are supposed to alternate between weapons per spawn. They can get a MK1, tac shotgun, or the weird ass black MK1 that PMCs get. Their things like belt and ammo change accordingly ofc. IDK why but they get "heavy beanbag slugs". Giving em Buckshot for now.
